"""The generated reference pages: read out of the source, not written by hand.

Four pages under docs/reference/ describe the shape of the package
itself, which is the one thing a hand-written page cannot be trusted to
keep complete. Diataxis asks reference material to mirror the structure
of the product it describes (https://diataxis.fr/reference/), so these
four mirror it by being generated from it:

    map.md     every package and every module, in the uses order
    ports.md   every port of decsim/ports.py, in pipeline order
    tables.md  every plug-in table and its rows
    cli.md     every command of the front and its flags

Run from the checkout with no argument to write all four. The uses order
is read from tools/check_uses_graph.py, so the map and the checker can
never disagree. tests/test_docs.py generates the four again and fails
when a committed page differs, so a page cannot drift from its code.
"""

import ast
import collections
import importlib.util
import pathlib
import re
import sys

TOOLS_FILE = pathlib.Path(__file__)
TOOLS_PATH = TOOLS_FILE.resolve()
TOOLS = TOOLS_PATH.parent
CHECKOUT = TOOLS.parent
BANNER = re.compile(r"^# -+\s*(.+?)\s*$")
SENTENCE_END = re.compile(r"[.!?](?=\s|$)")
ABBREVIATIONS = (
    "Sec",
    "Secs",
    "Fig",
    "Figs",
    "Eq",
    "Eqs",
    "Tab",
    "App",
    "Ref",
    "Ch",
    "No",
    "al",
    "cf",
    "vs",
    "i.e",
    "e.g",
)
UPPER_NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")
CRUMB = "[decsim docs](../README.md) › [Reference](README.md)"
GENERATED = (
    "This page is generated by `tools/docs_map.py` and checked by "
    "`tests/test_docs.py`. To change it, change the source it reads and "
    "run the tool again."
)


def uses_graph_tool():
    """tools/check_uses_graph.py, imported from beside this file."""
    path = TOOLS / "check_uses_graph.py"
    spec = importlib.util.spec_from_file_location("check_uses_graph", path)
    module = importlib.util.module_from_spec(spec)
    loader = spec.loader
    loader.exec_module(module)
    return module


def first_sentence(text: str) -> str:
    """The first sentence of a docstring, on one line.

    A period that closes an abbreviation the field writes constantly
    ("Sec. III C", "Fig. 12", "et al.") does not close the sentence, so
    the list below is checked before a period is believed.
    """
    opening = first_paragraph(text)
    found = SENTENCE_END.finditer(opening)
    for match in found:
        end = match.end()
        sentence = opening[:end]
        if _ends_a_sentence(sentence):
            return sentence
    return opening


def _ends_a_sentence(sentence: str) -> bool:
    """Whether the period that closes this candidate closes a sentence."""
    stripped = sentence.rstrip(".!?")
    words = stripped.split()
    if not words:
        return True
    last = words[-1]
    return last not in ABBREVIATIONS


def first_paragraph(text: str) -> str:
    """The opening paragraph of a docstring, on one line."""
    stripped = text.strip()
    paragraphs = stripped.split("\n\n")
    opening = paragraphs[0]
    unwrapped = opening.replace("\n", " ")
    words = unwrapped.split()
    return " ".join(words)


def module_summary(path: pathlib.Path) -> str:
    """The first sentence of a module's docstring."""
    tree = _parsed(path)
    text = ast.get_docstring(tree)
    if text is None:
        return ""
    return first_sentence(text)


def _parsed(path: pathlib.Path) -> ast.Module:
    """One source file as a syntax tree."""
    source = path.read_text()
    return ast.parse(source)


def _relative(path: pathlib.Path, checkout: pathlib.Path) -> str:
    """One file's path as a reader types it, from the checkout root."""
    relative = path.relative_to(checkout)
    return relative.as_posix()


def module_paths(package_root: pathlib.Path) -> list:
    """Every module under the package root, in path order."""
    tool = uses_graph_tool()
    return tool.source_paths(package_root)


def modules_by_package(package_root: pathlib.Path) -> dict:
    """Every module under the root, grouped by the package it belongs to."""
    tool = uses_graph_tool()
    paths = module_paths(package_root)
    grouped = collections.defaultdict(list)
    for path in paths:
        package = tool.package_of(path, package_root)
        grouped[package].append(path)
    return grouped


def package_levels(package_root: pathlib.Path) -> dict:
    """Each package's level in the uses order the checker reports."""
    tool = uses_graph_tool()
    edges = tool.read_edges(package_root)
    nodes = tool.nodes_of(edges)
    return tool.levels_of(edges, nodes)


# ------------------------------------------------------------- the map page


def _module_line(path: pathlib.Path, checkout: pathlib.Path) -> str:
    """One module's line of the map: its path, then what it is."""
    shown = _relative(path, checkout)
    summary = module_summary(path)
    return f"- `{shown}`: {summary}"


def _package_section(package: str, paths: list, checkout) -> list:
    """One package's heading and one line per module of it."""
    lines = [f"### {package}", ""]
    for path in paths:
        line = _module_line(path, checkout)
        lines.append(line)
    lines.append("")
    return lines


def _map_header() -> list:
    """The map page's title and the paragraph that says how to read it."""
    return [
        CRUMB,
        "",
        "# The map of the package",
        "",
        GENERATED,
        "",
        "Every module of `decsim/`, grouped by the package it belongs to",
        "and ordered by the level that package sits on. A package on",
        "level 0 imports no other `decsim` package. A package on level n",
        "imports one on level n minus one and none above it, so the",
        "levels above any line can be cut away and what is left still",
        "runs. The levels are the ones `tools/check_uses_graph.py`",
        "prints and `decsim/machine.py` names in its docstring. Each",
        "line is a module's path and the first sentence of its",
        "docstring.",
        "",
    ]


def _root_section(checkout: pathlib.Path) -> list:
    """The one module of the package root, which sits on no level."""
    path = checkout / "decsim" / "__init__.py"
    line = _module_line(path, checkout)
    return ["## The package root", "", line, ""]


def _level_sections(packages: list, grouped: dict, checkout) -> list:
    """Every package of one level, each with its modules."""
    lines = []
    for package in packages:
        paths = grouped[package]
        section = _package_section(package, paths, checkout)
        lines.extend(section)
    return lines


def map_page(checkout: pathlib.Path) -> str:
    """docs/reference/map.md: every package and module in the uses order."""
    package_root = checkout / "decsim"
    grouped = modules_by_package(package_root)
    levels = package_levels(package_root)
    by_level = collections.defaultdict(list)
    for package, level in levels.items():
        by_level[level].append(package)
    lines = _map_header()
    root_section = _root_section(checkout)
    lines.extend(root_section)
    for level in sorted(by_level):
        named_packages = by_level[level]
        packages = sorted(named_packages)
        named = ", ".join(packages)
        lines.append(f"## Level {level}: {named}")
        lines.append("")
        sections = _level_sections(packages, grouped, checkout)
        lines.extend(sections)
    return "\n".join(lines)


# ----------------------------------------------------------- the ports page


def _is_a_protocol(node: ast.ClassDef) -> bool:
    """Whether a class is written as a Protocol."""
    for base in node.bases:
        if not isinstance(base, ast.Name):
            continue
        if base.id == "Protocol":
            return True
    return False


def _method_row(child: ast.FunctionDef) -> str:
    """One method's row: its name, and the first sentence of its docstring."""
    text = ast.get_docstring(child)
    summary = ""
    if text is not None:
        summary = first_sentence(text)
    return f"| `{child.name}` | {summary} |"


def _method_rows(node: ast.ClassDef) -> list:
    """One row per method a port declares."""
    rows = []
    for child in node.body:
        if not isinstance(child, ast.FunctionDef):
            continue
        row = _method_row(child)
        rows.append(row)
    return rows


def _member_rows(node: ast.ClassDef) -> list:
    """One row per fact a port declares as a member rather than a method."""
    rows = []
    for child in node.body:
        if not isinstance(child, ast.AnnAssign):
            continue
        target = child.target
        annotation = ast.unparse(child.annotation)
        rows.append(f"| `{target.id}` | `{annotation}` |")
    return rows


def _member_table(node: ast.ClassDef) -> list:
    """The members table of one port, left out when it declares none."""
    rows = _member_rows(node)
    if not rows:
        return []
    lines = ["| Member | Type |", "| --- | --- |"]
    lines.extend(rows)
    lines.append("")
    return lines


def _method_table(node: ast.ClassDef) -> list:
    """The methods table of one port, left out when it declares none."""
    rows = _method_rows(node)
    if not rows:
        return []
    lines = ["| Method | What it does |", "| --- | --- |"]
    lines.extend(rows)
    lines.append("")
    return lines


def _port_section(node: ast.ClassDef) -> list:
    """One port: its name, what it is, its members and its methods."""
    lines = [f"### `{node.name}`", ""]
    text = ast.get_docstring(node)
    if text is not None:
        paragraph = first_paragraph(text)
        lines.append(paragraph)
        lines.append("")
    member_table = _member_table(node)
    lines.extend(member_table)
    method_table = _method_table(node)
    lines.extend(method_table)
    return lines


def _banners_of(source: str) -> list:
    """Each banner comment of the port file, as (line number, its words)."""
    found = []
    lines = source.splitlines()
    numbered = enumerate(lines, start=1)
    for number, line in numbered:
        match = BANNER.match(line)
        if match is not None:
            words = match.group(1)
            found.append((number, words))
    return found


def _ports_header(tree: ast.Module) -> list:
    """The ports page's title, and the port file's own opening paragraph."""
    lines = [CRUMB, "", "# The ports", "", GENERATED, ""]
    text = ast.get_docstring(tree)
    if text is not None:
        paragraph = first_paragraph(text)
        lines.append(paragraph)
        lines.append("")
    lines.append(
        "The headings are the port file's own section banners, so this "
        "page reads in the order `decsim/ports.py` reads: the order a "
        "readout travels."
    )
    lines.append("")
    return lines


def _port_classes(tree: ast.Module) -> list:
    """Every Protocol class of the port file, in file order."""
    found = []
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        if _is_a_protocol(node):
            found.append(node)
    return found


def _line_number(item: tuple) -> int:
    """The line one item of the port file sits on."""
    return item[0]


def _page_items(tree: ast.Module, source: str) -> list:
    """The banners and the ports of the port file, in the order they appear."""
    items = []
    banners = _banners_of(source)
    for number, words in banners:
        items.append((number, "banner", words))
    classes = _port_classes(tree)
    for node in classes:
        items.append((node.lineno, "port", node))
    return sorted(items, key=_line_number)


def _item_lines(kind: str, body) -> list:
    """One item of the port file rendered: a heading, or a whole port."""
    if kind == "banner":
        return [f"## {body}", ""]
    return _port_section(body)


def ports_page(checkout: pathlib.Path) -> str:
    """docs/reference/ports.md: every port, in the order of the port file."""
    path = checkout / "decsim" / "ports.py"
    source = path.read_text()
    tree = ast.parse(source)
    items = _page_items(tree, source)
    lines = _ports_header(tree)
    for _, kind, body in items:
        rendered = _item_lines(kind, body)
        lines.extend(rendered)
    return "\n".join(lines)


# ---------------------------------------------------------- the tables page


def _alias_targets(tree: ast.Module) -> dict:
    """Each module alias this module imports, by the file it names."""
    targets = {}
    for node in tree.body:
        if isinstance(node, ast.Import):
            plain = _import_aliases(node)
            targets.update(plain)
        if isinstance(node, ast.ImportFrom):
            named = _import_from_aliases(node)
            targets.update(named)
    return targets


def _import_aliases(node: ast.Import) -> dict:
    """`import decsim.a.b as name`: the dotted module each alias names."""
    targets = {}
    for alias in node.names:
        if alias.asname is None:
            continue
        targets[alias.asname] = alias.name
    return targets


def _import_from_aliases(node: ast.ImportFrom) -> dict:
    """`from decsim.a import b`: the dotted module each bound name names."""
    targets = {}
    if node.module is None:
        return targets
    for alias in node.names:
        bound = alias.asname
        if bound is None:
            bound = alias.name
        targets[bound] = f"{node.module}.{alias.name}"
    return targets


def _module_file(dotted: str, checkout: pathlib.Path):
    """The file a dotted decsim module name lives in, or None."""
    parts = dotted.split(".")
    joined = "/".join(parts)
    module = checkout / f"{joined}.py"
    if module.exists():
        return module
    package = checkout / joined / "__init__.py"
    if package.exists():
        return package
    return None


def _class_summary(path: pathlib.Path, name: str) -> str:
    """The first sentence of one class's docstring in one module."""
    tree = _parsed(path)
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        if node.name == name:
            return _class_docstring(node)
    return ""


def _class_docstring(node: ast.ClassDef) -> str:
    """One class's first sentence, empty when it carries no docstring."""
    text = ast.get_docstring(node)
    if text is None:
        return ""
    return first_sentence(text)


def _row_target(value: ast.AST, module: pathlib.Path, checkout) -> tuple:
    """The file and class name one table value names, as (path, name)."""
    if isinstance(value, ast.Name):
        return (module, value.id)
    if not isinstance(value, ast.Attribute):
        return (None, None)
    holder = value.value
    if not isinstance(holder, ast.Name):
        return (None, None)
    tree = _parsed(module)
    aliases = _alias_targets(tree)
    dotted = aliases.get(holder.id)
    if dotted is None:
        return (None, None)
    path = _module_file(dotted, checkout)
    return (path, value.attr)


def _row_line(key: str, value: ast.AST, module, checkout) -> str:
    """One table row: its yaml name, the class it names, and what that is."""
    if isinstance(value, ast.Constant):
        return f"| `{key}` | none | the check is off |"
    path, name = _row_target(value, module, checkout)
    if path is None:
        return f"| `{key}` | | |"
    shown = _relative(path, checkout)
    summary = _class_summary(path, name)
    return f"| `{key}` | `{name}` in `{shown}` | {summary} |"


def _row_lines(node: ast.Dict, module: pathlib.Path, checkout) -> list:
    """Every row of one table, in the order the code declares them."""
    lines = []
    pairs = zip(node.keys, node.values)
    for key_node, value in pairs:
        key = key_node.value
        line = _row_line(key, value, module, checkout)
        lines.append(line)
    return lines


def _table_dicts(path: pathlib.Path) -> dict:
    """Every module-level table of classes in one module, by its name."""
    tree = _parsed(path)
    found = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        named = _class_table(node)
        if named is not None:
            found.update(named)
    return found


def _class_table(node: ast.Assign):
    """One assignment, when it declares a dict of classes under a name."""
    if len(node.targets) != 1:
        return None
    target = node.targets[0]
    if not isinstance(target, ast.Name):
        return None
    if not UPPER_NAME.match(target.id):
        return None
    if not isinstance(node.value, ast.Dict):
        return None
    if not _holds_a_class(node.value):
        return None
    return {target.id: node.value}


def _holds_a_class(node: ast.Dict) -> bool:
    """Whether a dict names at least one class, rather than plain values."""
    for value in node.values:
        if isinstance(value, ast.Name):
            return True
        if isinstance(value, ast.Attribute):
            return True
    return False


def _lookup_keys(package_root: pathlib.Path) -> dict:
    """Every yaml key each table is looked up under, from tables.row calls."""
    found = collections.defaultdict(list)
    paths = module_paths(package_root)
    for path in paths:
        _collect_lookup_keys(path, found)
    return found


def _collect_lookup_keys(path: pathlib.Path, found: dict) -> None:
    """The tables.row calls of one module, by the table each one reads."""
    tree = _parsed(path)
    walked = ast.walk(tree)
    for node in walked:
        if not isinstance(node, ast.Call):
            continue
        pair = _lookup_pair(node)
        if pair is not None:
            _record_lookup(pair, found)


def _record_lookup(pair: tuple, found: dict) -> None:
    """One table's yaml key, kept once however many sites read it."""
    table, key = pair
    keys = found[table]
    if key not in keys:
        keys.append(key)


def _lookup_pair(node: ast.Call):
    """A tables.row call, as (the table's name, the yaml key it reads)."""
    function = node.func
    if not isinstance(function, ast.Attribute):
        return None
    if function.attr != "row":
        return None
    if len(node.args) < 2:
        return None
    table = _table_named(node.args[0])
    if table is None:
        return None
    key = _key_text(node.args[1])
    if key is None:
        return None
    return (table, key)


def _table_named(node: ast.AST):
    """The table's own name, whether the caller wrote it bare or qualified."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def _key_text(node: ast.AST):
    """The yaml key one lookup names, with a tier written as a placeholder."""
    if isinstance(node, ast.Constant):
        return node.value
    if not isinstance(node, ast.JoinedStr):
        return None
    words = []
    for part in node.values:
        word = _key_part(part)
        words.append(word)
    return "".join(words)


def _key_part(part: ast.AST) -> str:
    """One piece of a formatted key: its text, or the name it fills in."""
    if isinstance(part, ast.Constant):
        return part.value
    value = part.value
    if isinstance(value, ast.Name):
        return f"<{value.id}>"
    return "<...>"


def tables_of(checkout: pathlib.Path) -> list:
    """Every plug-in table of the package, as (name, dict node, its module)."""
    package_root = checkout / "decsim"
    keys = _lookup_keys(package_root)
    paths = module_paths(package_root)
    found = []
    for path in paths:
        declared = _table_dicts(path)
        named = _looked_up(declared, path, keys)
        found.extend(named)
    return sorted(found)


def _looked_up(declared: dict, path: pathlib.Path, keys: dict) -> list:
    """The tables of one module that a yaml key names, sorted by name."""
    found = []
    for name, node in declared.items():
        if name not in keys:
            continue
        found.append((name, path, node))
    return sorted(found)


def _table_section(entry: tuple, keys: dict, checkout) -> list:
    """One table: where it lives, the yaml key that reads it, and its rows."""
    name, module, node = entry
    shown = _relative(module, checkout)
    named_keys = keys[name]
    quoted = _quoted_keys(named_keys)
    lines = [f"## `{name}`", ""]
    lines.append(f"In `{shown}`. A yaml names a row of it under {quoted}.")
    lines.append("")
    lines.append("| Row | Class | What it is |")
    lines.append("| --- | --- | --- |")
    rows = _row_lines(node, module, checkout)
    lines.extend(rows)
    lines.append("")
    return lines


def _quoted_keys(named_keys: list) -> str:
    """The yaml keys of one table, as a reader reads them in a sentence."""
    quoted = []
    for key in named_keys:
        quoted.append(f"`{key}`")
    return " and ".join(quoted)


def _tables_header(count: int) -> list:
    """The tables page's title and the paragraph that says how to read it."""
    return [
        CRUMB,
        "",
        "# The plug-in tables",
        "",
        GENERATED,
        "",
        "A pluggable part of the machine is a table of rows, and there",
        f"are {count} of them. A row is one name a yaml file may write",
        "and one class the machine builds for it. The table lives beside",
        "the classes it lists, in the package that owns the part, and",
        "`decsim/tables.py` is the one function that reads them all, so",
        "a name that is not a row is refused the same way everywhere",
        "with the rows printed. Each class fills the port named in",
        "[`docs/reference/ports.md`](ports.md).",
        "",
    ]


def tables_page(checkout: pathlib.Path) -> str:
    """docs/reference/tables.md: every plug-in table and every row of it."""
    package_root = checkout / "decsim"
    keys = _lookup_keys(package_root)
    entries = tables_of(checkout)
    count = len(entries)
    lines = _tables_header(count)
    for entry in entries:
        section = _table_section(entry, keys, checkout)
        lines.extend(section)
    return "\n".join(lines)


# ------------------------------------------------------------- the cli page


def _parser_name(node: ast.Assign):
    """The name an ArgumentParser is assigned to, when this line makes one."""
    if len(node.targets) != 1:
        return None
    target = node.targets[0]
    if not isinstance(target, ast.Name):
        return None
    if not isinstance(node.value, ast.Call):
        return None
    call = node.value
    if not _is_parser_call(call):
        return None
    return target.id


def _is_parser_call(call: ast.Call) -> bool:
    """Whether a call builds an argparse parser."""
    function = call.func
    if not isinstance(function, ast.Attribute):
        return False
    return function.attr == "ArgumentParser"


def _keyword_text(call: ast.Call, name: str):
    """One keyword argument of a call, as its source text."""
    for keyword in call.keywords:
        if keyword.arg != name:
            continue
        return ast.unparse(keyword.value)
    return None


def _program_of(call: ast.Call):
    """The prog= a parser is built with."""
    return _keyword_text(call, "prog")


def _argument_row(call: ast.Call) -> str:
    """One add_argument call as a row: its name, its default and its help."""
    first = call.args[0]
    name = first.value
    helped = _keyword_text(call, "help")
    if helped is None:
        helped = ""
    trimmed = helped.strip("'\"")
    default = _argument_default(call, name)
    return f"| `{name}` | {default} | {trimmed} |"


def _argument_default(call: ast.Call, name: str) -> str:
    """What one argument is worth when the command line leaves it out."""
    default = _keyword_text(call, "default")
    if default is not None:
        return default
    action = _keyword_text(call, "action")
    if action is not None:
        return "off unless the flag is given"
    if name.startswith("-"):
        return "None"
    return "required"


def _argument_rows(function: ast.FunctionDef, parser: str) -> list:
    """Every add_argument on one parser inside one function."""
    rows = []
    walked = ast.walk(function)
    for node in walked:
        if not _is_add_argument(node, parser):
            continue
        row = _argument_row(node)
        rows.append(row)
    return rows


def _is_add_argument(node: ast.AST, parser: str) -> bool:
    """Whether one node is `parser.add_argument(...)` on that parser."""
    if not isinstance(node, ast.Call):
        return False
    called = node.func
    if not isinstance(called, ast.Attribute):
        return False
    if called.attr != "add_argument":
        return False
    holder = called.value
    if not isinstance(holder, ast.Name):
        return False
    return holder.id == parser


def _parsers_of(path: pathlib.Path) -> list:
    """Every command one module defines, as (its prog, its argument rows)."""
    tree = _parsed(path)
    found = []
    walked = ast.walk(tree)
    for node in walked:
        if not isinstance(node, ast.FunctionDef):
            continue
        built = _function_parsers(node)
        found.extend(built)
    return found


def _function_parsers(function: ast.FunctionDef) -> list:
    """The parsers one function builds, each with the arguments it takes."""
    found = []
    walked = ast.walk(function)
    for node in walked:
        if not isinstance(node, ast.Assign):
            continue
        built = _assigned_parser(node, function)
        found.extend(built)
    return found


def _assigned_parser(node: ast.Assign, function: ast.FunctionDef) -> list:
    """One assignment, when it builds a parser, with that parser's arguments."""
    parser = _parser_name(node)
    if parser is None:
        return []
    program = _program_of(node.value)
    if program is None:
        return []
    trimmed = program.strip("'\"")
    rows = _argument_rows(function, parser)
    return [(trimmed, rows)]


def _cli_header(path: pathlib.Path) -> list:
    """The cli page's title and the command file's own usage block."""
    tree = _parsed(path)
    text = ast.get_docstring(tree)
    paragraph = first_paragraph(text)
    return [
        CRUMB,
        "",
        "# The commands",
        "",
        GENERATED,
        "",
        paragraph,
        "",
        "Every argument below is read from the `argparse` definition "
        "that parses it. An argument with no default is required.",
        "",
    ]


def _command_section(entry: tuple) -> list:
    """One command: its name, and the table of what it takes."""
    program, rows = entry
    lines = [f"## `{program}`", ""]
    if not rows:
        lines.append("Takes no argument of its own.")
        lines.append("")
        return lines
    lines.append("| Argument | Default | What it is |")
    lines.append("| --- | --- | --- |")
    lines.extend(rows)
    lines.append("")
    return lines


def cli_page(checkout: pathlib.Path) -> str:
    """docs/reference/cli.md: every command of the front and its arguments."""
    front = checkout / "decsim" / "front"
    command = front / "command.py"
    lines = _cli_header(command)
    globbed = front.glob("*.py")
    paths = sorted(globbed)
    entries = []
    for path in paths:
        found = _parsers_of(path)
        entries.extend(found)
    for entry in sorted(entries):
        section = _command_section(entry)
        lines.extend(section)
    return "\n".join(lines)


# ------------------------------------------------------------- the four pages


def pages(checkout: pathlib.Path) -> dict:
    """The four generated pages, by their file name under docs/reference/."""
    return {
        "map.md": map_page(checkout),
        "ports.md": ports_page(checkout),
        "tables.md": tables_page(checkout),
        "cli.md": cli_page(checkout),
    }


def main(arguments) -> int:
    """Write the four generated pages under docs/reference/."""
    checkout = CHECKOUT
    if arguments:
        checkout = pathlib.Path(arguments[0])
    written = pages(checkout)
    for name, text in written.items():
        path = checkout / "docs" / "reference" / name
        path.write_text(text)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    exit_code = main(sys.argv[1:])
    sys.exit(exit_code)
