"""The parts page: every settings record a machine is built from.

docs/reference/parts.md lists each settings record of decsim/, grouped
by package: its name, its module, its docstring, the records it extends,
and each field with its type and default. A field's unit is in its name.
A slot a researcher fills with a record of their own is typed by a
Protocol named for the record it takes, and the page lists its members.
gem5 generates its reference from its classes the same way, so the page
cannot fall behind the code. The run side's records (decsim/experiments/)
and the build's own (decsim/build/) are no part a user sets.

Run it to write the page of the checkout it is in; it takes no argument.
tests/test_docs.py generates it again and fails when the committed page
differs.
"""

import ast
import dataclasses
import pathlib
import re
import sys
from typing import Optional

TOOLS_FILE = pathlib.Path(__file__)
TOOLS_PATH = TOOLS_FILE.resolve()
CHECKOUT = TOOLS_PATH.parent.parent
PAGE_NAME = "parts.md"
SENTENCE_END = re.compile(r"[.!?](?=\s|$)")
# periods the field writes inside a sentence ("Sec. III C", "et al.")
ABBREVIATIONS = (
    "Sec",
    "Secs",
    "Fig",
    "Figs",
    "Eq",
    "Eqs",
    "Tab",
    "App",
    "Ref",
    "Ch",
    "No",
    "al",
    "cf",
    "vs",
    "i.e",
    "e.g",
)
# a record is a dataclass named for what it holds
RECORD_NAME_ENDINGS = ("Settings", "Config")
SKIPPED_PACKAGES = ("decsim/experiments", "decsim/build")
FIELD_FUNCTIONS = ("field", "dataclasses.field")
CRUMB = "[decsim docs](../README.md) › [Reference](README.md)"
GENERATED = (
    "This page is generated by `tools/docs_map.py` and checked by "
    "`tests/test_docs.py`. To change it, change the source it reads and "
    "run the tool again."
)
INTRODUCTION = (
    "A machine is one `MachineSettings` (`decsim/settings.py`), a record "
    "of records: each field holds the settings of one part, and a part's "
    "record holds the records of the components it builds. A record with "
    "a `build` method builds its component. A field with no default is "
    "required, and a field's unit is in its name."
)


def parts_page(checkout: pathlib.Path) -> str:
    """docs/reference/parts.md: every settings record, by package."""
    records_by_package = _records_by_package(checkout)
    lines = [CRUMB, "", "# Parts", "", GENERATED, "", INTRODUCTION, ""]
    for package, records in records_by_package.items():
        lines.extend([f"## {package}", ""])
        for record in records:
            section = _record_section(record, checkout)
            lines.extend(section)
    text = "\n".join(lines)
    return text.rstrip("\n") + "\n"


def first_sentence(text: str) -> str:
    """The first sentence of a docstring, on one line."""
    paragraphs = _paragraphs(text)
    opening = paragraphs[0]
    found = SENTENCE_END.finditer(opening)
    for match in found:
        end = match.end()
        sentence = opening[:end]
        if _ends_a_sentence(sentence):
            return sentence
    return opening


def main() -> int:
    """Write the parts page under docs/reference/."""
    text = parts_page(CHECKOUT)
    path = CHECKOUT / "docs" / "reference" / PAGE_NAME
    path.write_text(text)
    print(f"wrote {path}")
    return 0


@dataclasses.dataclass(frozen=True)
class _Record:
    """One settings record: its name, its module, its text, its node."""

    name: str
    path: pathlib.Path
    paragraphs: tuple
    node: ast.ClassDef


def _records_by_package(checkout: pathlib.Path) -> dict:
    """Every record of decsim/, by its package, the root package first."""
    package_root = checkout / "decsim"
    found_paths = package_root.rglob("*.py")
    module_paths = sorted(found_paths)
    grouped = {}
    for path in module_paths:
        relative = path.relative_to(checkout)
        package = relative.parent.as_posix()
        if package.startswith(SKIPPED_PACKAGES):
            continue
        records = _records_of(path)
        if not records:
            continue
        package_records = grouped.setdefault(package, [])
        package_records.extend(records)
    package_names = sorted(grouped)
    return {package: grouped[package] for package in package_names}


def _records_of(path: pathlib.Path) -> list:
    """The records one module defines, nested Settings classes included."""
    source = path.read_text()
    tree = ast.parse(source)
    records = []
    _collect_records(tree, path, "", "", records)
    return records


def _collect_records(node, path, outer_name, outer_text, records) -> None:
    """The records under one node, each named by its enclosing classes.

    A nested Settings with no docstring of its own reads as the first
    sentence of the class it sits in.
    """
    for child in ast.iter_child_nodes(node):
        if not isinstance(child, ast.ClassDef):
            continue
        name = f"{outer_name}{child.name}"
        docstring = ast.get_docstring(child)
        paragraphs = (outer_text,)
        if docstring is not None:
            paragraphs = _paragraphs(docstring)
        if _is_a_record(child) or _is_a_slot(child):
            record = _Record(name, path, paragraphs, child)
            records.append(record)
        opening = paragraphs[0]
        summary = first_sentence(opening)
        _collect_records(child, path, f"{name}.", summary, records)


def _is_a_record(node: ast.ClassDef) -> bool:
    """A dataclass whose name says it holds settings."""
    if not node.name.endswith(RECORD_NAME_ENDINGS):
        return False
    decorators = [ast.unparse(decorator) for decorator in node.decorator_list]
    return any("dataclass" in decorator for decorator in decorators)


def _is_a_slot(node: ast.ClassDef) -> bool:
    """A Protocol named for the settings record a slot takes."""
    if not node.name.endswith(RECORD_NAME_ENDINGS):
        return False
    bases = _base_names(node)
    return "Protocol" in bases


def _record_section(record: _Record, checkout: pathlib.Path) -> list:
    """One record's heading, its module and text, and its fields."""
    module_path = record.path.relative_to(checkout)
    module = module_path.as_posix()
    opening, *rest = record.paragraphs
    lines = [f"### `{record.name}`", "", f"`{module}`. {opening}", ""]
    for paragraph in rest:
        lines.extend([paragraph, ""])
    extended = _extended_records(record.node)
    if extended:
        lines.extend([f"It extends {extended}, and holds its fields.", ""])
    if _is_a_slot(record.node):
        member_lines = _member_table(record.node)
        lines.extend(member_lines)
        return lines
    rows = _field_rows(record.node)
    if rows:
        lines.extend(["| Field | Type | Default |", "| --- | --- | --- |"])
        lines.extend(rows)
        lines.append("")
    return lines


def _base_names(node: ast.ClassDef) -> list:
    """The classes this one names as its bases, as the source writes them."""
    names = []
    for base in node.bases:
        name = ast.unparse(base)
        names.append(name)
    return names


def _extended_records(node: ast.ClassDef) -> str:
    """The records this one subclasses, in backticks; empty for none."""
    extended = []
    for name in _base_names(node):
        if name.endswith(RECORD_NAME_ENDINGS):
            extended.append(f"`{name}`")
    return ", ".join(extended)


def _member_table(node: ast.ClassDef) -> list:
    """A slot's members: each attribute's type, each method's call."""
    rows = []
    for child in node.body:
        if isinstance(child, ast.AnnAssign):
            row = _attribute_row(child)
            rows.append(row)
        if isinstance(child, ast.FunctionDef):
            row = _method_row(child)
            rows.append(row)
    if not rows:
        return []
    return ["| Member | Type |", "| --- | --- |", *rows, ""]


def _attribute_row(node: ast.AnnAssign) -> str:
    """One attribute of a slot and its type."""
    annotation = ast.unparse(node.annotation)
    type_cell = _cell(annotation)
    return f"| `{node.target.id}` | {type_cell} |"


def _method_row(node: ast.FunctionDef) -> str:
    """One method of a slot, as its call, and what it returns."""
    arguments = ast.unparse(node.args)
    returns = "None"
    if node.returns is not None:
        returns = ast.unparse(node.returns)
    call_cell = _cell(f"{node.name}({arguments})")
    returns_cell = _cell(returns)
    return f"| {call_cell} | {returns_cell} |"


def _field_rows(node: ast.ClassDef) -> list:
    """One table row per field the record declares."""
    rows = []
    for child in node.body:
        if not isinstance(child, ast.AnnAssign):
            continue
        annotation = ast.unparse(child.annotation)
        if annotation.startswith(("ClassVar", "typing.ClassVar")):
            continue
        name = child.target.id
        default = _default_text(child.value)
        default_cell = "required"
        if default is not None:
            default_cell = _cell(default)
        annotation_cell = _cell(annotation)
        row = f"| `{name}` | {annotation_cell} | {default_cell} |"
        rows.append(row)
    return rows


def _default_text(value) -> Optional[str]:
    """A field's default as the source writes it; None for no default."""
    if value is None:
        return None
    is_field_call = isinstance(value, ast.Call) and (
        ast.unparse(value.func) in FIELD_FUNCTIONS
    )
    if not is_field_call:
        return ast.unparse(value)
    for keyword in value.keywords:
        if keyword.arg == "default":
            return ast.unparse(keyword.value)
        if keyword.arg == "default_factory":
            factory = ast.unparse(keyword.value)
            return f"{factory}()"
    return None


def _cell(text: str) -> str:
    """Source text as a table cell: in backticks, its pipes escaped."""
    escaped = text.replace("|", "\\|")
    return f"`{escaped}`"


def _paragraphs(text: str) -> tuple:
    """A docstring's paragraphs, each on one line."""
    stripped = text.strip()
    paragraphs = []
    for paragraph in stripped.split("\n\n"):
        words = paragraph.split()
        one_line = " ".join(words)
        paragraphs.append(one_line)
    return tuple(paragraphs)


def _ends_a_sentence(sentence: str) -> bool:
    """Whether the period that closes this candidate closes a sentence."""
    stripped = sentence.rstrip(".!?")
    words = stripped.split()
    if not words:
        return True
    last = words[-1]
    return last not in ABBREVIATIONS


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
